document.write('your name="amal"')
document.write("<br>")
document.write('your name=\"amal\"')
document.write("<br>")
var s = ("hello, world" )
document.write(s.charAt(0))
document.write("<br>")
document.write(s.charAt(5))
document.write("<br>")
document.write(s.charAt(s.length-1))
document.write("<br>")
